### ISSUE TITLE
SDK 23 (6.0) compatibility

### ISSUE THREAD

**Issue by AMZMA** [Aefyr/Eris#1]
an app on SDK 23 can't be sniffed (Mangarock) on Charles, so I tried to use this module but I couldn't install it.

**Comment by Aefyr** [comment]
I'm not sure Eris will work on marshmallow and I've got no way to test it out, but if you wanna try it, I made a version with minSdk lowered to 21. Please tell me if it works

[eris21.zip](https://github.com/Aefyr/Eris/files/2730520/eris21.zip)

**Comment by Aefyr** [comment]
Actually classes which Eris hooks don't exist on Android versions lower than 7.0. So I guess there is no way it will work there.
